"""A prebuilt binary from a GitHub release: download, verify, place under tools/<id>/, launcher in the bin dir."""

from __future__ import annotations

from pathlib import Path

from exakit.adapters.net.github import download_url
from exakit.domain.errors import Failed

from .base import LifecycleBase, make_executable, temp_dir


class BinaryLifecycle(LifecycleBase):
    @property
    def home(self) -> Path:
        return self.ctx.paths.home / self.addon.id

    @property
    def engine(self) -> Path:
        exe = ".exe" if self.ctx.platform.os == "windows" else ""
        return self.home / "libexec" / f"{self.addon.id.replace('-', '_')}{exe}"

    def asset_name(self, version: str) -> str:
        """The release asset for this platform: the catalog's ``assets`` map, else ``<id>-<os>-<arch>``."""
        assets = self.addon.source.get("assets") or {}
        return str(assets.get(self.ctx.platform.platform_key) or f"{self.addon.id}-{self.ctx.platform.os}-{self.ctx.platform.arch}")

    def release_tag(self, version: str) -> str:
        return str(self.addon.source.get("tag", "{version}")).format(version=version)

    def repo(self) -> str:
        """The repository the release lives in: the kit's own when the catalog says ``mirror: kit``."""
        if self.addon.source.get("mirror") == "kit":
            return self.ctx.kit_repo
        return str(self.addon.source["repo"])

    def digest_key(self, version: str) -> str:
        keys = self.addon.source.get("digest_keys") or {}
        return str(keys.get(self.ctx.platform.platform_key) or self.ctx.platform.platform_key)

    def installed_version(self) -> str | None:
        recorded = self.recorded("version")
        return str(recorded) if recorded and self.engine.exists() else None

    def fetch_engine(self, version: str, dest: Path) -> None:
        asset = self.asset_name(version)
        tag = self.release_tag(version)
        self.fetch_verified(download_url(self.repo(), tag, asset, endpoints=self.ctx.catalog.kit.endpoints), dest, digest=self.published_digest(version, self.digest_key(version)),
                            what=f"{self.addon.id} {version}", repo=self.repo(), tag=tag, asset=asset)

    def launcher_content(self) -> str | None:
        if not self.addon.launcher:
            return None
        return f'#!/bin/sh\n# {self.addon.launcher} launcher - generated by the Exasol Personal Local Starter Kit.\nexec "{self.engine}" "$@"\n'

    def write_launchers(self) -> None:
        content = self.launcher_content()
        if content and self.addon.launcher:
            self.write_launcher(self.addon.launcher, content)

    def install(self, version: str) -> None:
        ok, reason = self.applicable()
        if not ok:
            raise Failed(reason)
        force = self.ctx.env.get("EXAKIT_FORCE_COMPONENT_INSTALL") == "1"
        if self.installed_version() == version and not force:
            self.ctx.ui.ok(f"{self.addon.id} {version} is already installed")
            return
        self.ctx.ui.info(f"Installing {self.addon.id} {version} (prebuilt)")
        with temp_dir(f"exakit-{self.addon.id}-") as tmp:
            staged = Path(tmp) / "engine"
            self.fetch_engine(version, staged)
            self.engine.parent.mkdir(parents=True, exist_ok=True)
            staged.replace(self.engine)
        make_executable(self.engine)
        if not self.ctx.runner.run([str(self.engine), "--help"], timeout=30).ok:
            raise Failed(f"the prebuilt {self.addon.id} does not run on this machine (see log)")
        self.after_engine(version)
        self.write_launchers()
        self.record(version=version, engine=str(self.engine), command=str(self.ctx.paths.bin_dir / self.addon.launcher) if self.addon.launcher else None)
        self.ctx.ui.ok(f"{self.addon.id} {version} installed")

    def after_engine(self, version: str) -> None:
        return None

    def repair(self) -> None:
        self.write_launchers()

    def uninstall(self, *, dry_run: bool) -> list[str]:
        removed = self.remove_paths([self.home] + ([self.ctx.paths.bin_dir / self.addon.launcher] if self.addon.launcher else []), dry_run=dry_run)
        if not dry_run:
            self.forget()
            self.ctx.ui.ok(f"{self.addon.id} removed - reinstall any time with: exakit marketplace")
        return removed
