"""dbt-exasol: dbt with the Exasol adapter in its own venv, a generated profile, a launcher named dbt-exasol."""

from __future__ import annotations

import socket
from pathlib import Path

from exakit.adapters.fs.atomic import atomic_write_text
from exakit.lifecycles.base import temp_dir
from exakit.lifecycles.python_venv import PythonVenvLifecycle
import contextlib

PROFILE_NAME = "exasol_starter_kit"
SCHEMA = "DBT"

PROFILES = """# profiles.yml - generated by the Exasol Personal Local Starter Kit.
#
# Regenerated by `exakit update dbt-exasol`, so edits here do not survive.
# Your own ~/.dbt/profiles.yml is never read or written by the kit; the
# dbt-exasol launcher points dbt at THIS directory with DBT_PROFILES_DIR,
# and exporting your own DBT_PROFILES_DIR overrides that.
#
# The password is not stored here. The launcher reads it from the kit's
# credential file at run time into DBT_ENV_SECRET_EXASOL_PASSWORD, a name
# dbt scrubs from its own logs and artifacts.
{profile}:
  target: dev
  outputs:
    dev:
      type: exasol
      threads: 1
      dsn: {dsn}
      user: {user}
      password: "{{{{ env_var('DBT_ENV_SECRET_EXASOL_PASSWORD') }}}}"
      # Required by dbt-core as a profile field; Exasol has no multi-database
      # concept, so the value is not used for anything.
      dbname: DB
      schema: {schema}
      encryption: true
      # The kit's local runtime speaks TLS with a self-signed certificate.
      validate_server_certificate: false
"""

LAUNCHER = """#!/bin/sh
# dbt-exasol launcher - generated by the Exasol Personal Local Starter Kit.
# Runs the kit's dbt with the Exasol adapter against the local database:
#   dbt-exasol debug --connection     check the connection
#   dbt-exasol run                    run your models (profile: {profile})
if [ -z "${{DBT_ENV_SECRET_EXASOL_PASSWORD:-}}" ] && [ -r "{pwfile}" ]; then
    DBT_ENV_SECRET_EXASOL_PASSWORD="$(cat "{pwfile}")"
    export DBT_ENV_SECRET_EXASOL_PASSWORD
fi
: "${{DBT_PROFILES_DIR:={profiles_dir}}}"
export DBT_PROFILES_DIR
exec "{dbt}" "$@"
"""


class Lifecycle(PythonVenvLifecycle):
    seed = False

    @property
    def home(self) -> Path:
        return self.ctx.paths.home / "dbt"

    def write_profile(self) -> None:
        dsn, user, _ = self.runtime_credentials()
        if not dsn:
            self.ctx.ui.warn("No database DSN is recorded yet - the dbt profile has no address until the kit install completes.")
        self.home.mkdir(parents=True, exist_ok=True)
        atomic_write_text(self.home / "profiles.yml", PROFILES.format(profile=PROFILE_NAME, dsn=dsn, user=user, schema=SCHEMA), mode=0o600)

    def launcher_content(self) -> str | None:
        _, _, pw_file = self.runtime_credentials()
        return LAUNCHER.format(profile=PROFILE_NAME, pwfile=pw_file or "", profiles_dir=self.home, dbt=self.uv().bin_of(self.venv, "dbt"))

    def write_launchers(self) -> None:
        self.write_profile()
        super().write_launchers()

    def install(self, version: str) -> None:
        super().install(version)
        self.record(profiles_dir=str(self.home), profile=PROFILE_NAME)

    def db_reachable(self) -> bool:
        dsn, _, _ = self.runtime_credentials()
        host, _, port = dsn.rpartition(":")
        if not host or not port.isdigit():
            return False
        try:
            with socket.create_connection((host, int(port)), timeout=2):
                return True
        except OSError:
            return False

    def validate(self) -> None:
        if not self.python.exists():
            return
        if not self.ctx.runner.run([str(self.python), "-c", "import dbt.adapters.exasol"], timeout=60).ok:
            self.ctx.ui.warn("dbt-exasol did not import from its environment - repair with: exakit update dbt-exasol")
            self.record(validated=False)
            return
        if not self.db_reachable():
            self.record(validated=True, validated_by="import")
            return
        _, _, pw_file = self.runtime_credentials()
        password = Path(pw_file).read_text(encoding="utf-8") if pw_file and Path(pw_file).exists() else ""
        with temp_dir("exakit-dbt-") as tmp:
            (Path(tmp) / "dbt_project.yml").write_text(f'name: exakit_probe\nversion: "1.0.0"\nconfig-version: 2\nprofile: {PROFILE_NAME}\n')
            done = self.ctx.runner.run([str(self.uv().bin_of(self.venv, "dbt")), "debug", "--connection"], cwd=Path(tmp), timeout=60,
                                       env={"DBT_ENV_SECRET_EXASOL_PASSWORD": password, "DBT_PROFILES_DIR": str(self.home)})
        if done.ok:
            self.record(validated=True, validated_by="connection")
            self.ctx.ui.ok(f"dbt-exasol connects to the database (profile: {PROFILE_NAME})")
        else:
            self.record(validated=False, validated_by="connection")
            self.ctx.ui.warn("dbt could not connect to the database - check with: dbt-exasol debug --connection")

    def summary(self) -> str | None:
        return "build SQL models: dbt-exasol"

    def system_present(self) -> bool:
        found = self.ctx.runner.which("dbt")
        if found and str(self.venv) not in found and str(self.ctx.paths.home) not in found:
            done = self.ctx.runner.run([found, "--version"], timeout=60)
            if "exasol" in (done.out + done.err).lower():
                return True
        return False

    def uninstall(self, *, dry_run: bool) -> list[str]:
        removed = self.remove_paths([self.venv, self.ctx.paths.bin_dir / "dbt-exasol", self.home / "profiles.yml"], dry_run=dry_run)
        if dry_run:
            self.ctx.ui.text("  (anything else in that folder is left alone)")
            return removed
        with contextlib.suppress(OSError):
            self.home.rmdir()
        self.forget()
        self.ctx.ui.ok("dbt-exasol removed - reinstall any time with: exakit marketplace")
        return removed
