"""Exasol Scheduler: a prebuilt engine, a dedicated database user, a supervising launcher, a service."""

from __future__ import annotations

import subprocess
from pathlib import Path

from exakit.adapters.fs.credentials import CredentialStore
from exakit.adapters.net.github import release_assets
from exakit.adapters.process.services import ServiceSpec
from exakit.domain.errors import Failed
from exakit.lifecycles.base import ServiceHooks, wait_for
from exakit.lifecycles.binary import BinaryLifecycle

DB_USER = "scheduler_svc"
SCHEMA = "SCHED"

LAUNCHER = """#!/bin/sh
# exasol-scheduler launcher - generated by the Exasol Personal Local Starter Kit.
# One instance per task table: a second poller would run every job twice.
PIDFILE="{pidfile}"
ENGINE="{engine}"
if [ -f "$PIDFILE" ]; then
    _pid="$(cat "$PIDFILE" 2>/dev/null)"
    case "$_pid" in ''|*[!0-9]*) ;; *) if kill -0 "$_pid" 2>/dev/null; then
        printf 'exasol-scheduler is already running (pid %s).\\n' "$_pid"
        printf 'One instance per task table: a second poller would run every job twice.\\n'
        printf 'State: exakit status   Logs: exakit logs exasol-scheduler -f   Stop: exakit stop\\n'
        exit 0; fi ;; esac
fi
printf '%s\\n' "$$" > "$PIDFILE" 2>/dev/null || true
trap 'rm -f "$PIDFILE"' EXIT
rm -f "{giveup}" 2>/dev/null || true
[ -n "${{EXA_HOST:-}}" ] || {{ EXA_HOST="{host}"; export EXA_HOST; }}
[ -n "${{EXA_PORT:-}}" ] || {{ EXA_PORT="{port}"; export EXA_PORT; }}
[ -n "${{EXA_USER:-}}" ] || {{ EXA_USER="{user}"; export EXA_USER; }}
[ -n "${{EXA_TLS:-}}" ] || {{ EXA_TLS="true"; export EXA_TLS; }}
[ -n "${{EXA_VALIDATE_SERVER_CERT:-}}" ] || {{ EXA_VALIDATE_SERVER_CERT="false"; export EXA_VALIDATE_SERVER_CERT; }}
[ -n "${{EXA_SCHEMA:-}}" ] || {{ EXA_SCHEMA="{schema}"; export EXA_SCHEMA; }}
if [ -z "${{EXA_PASSWORD:-}}" ]; then
    if [ ! -r "{pwfile}" ]; then
        printf 'exasol-scheduler: credential file missing or unreadable: {pwfile}\\n' >&2
        printf 'Repair with: exakit update exasol-scheduler\\n' >&2; exit 1
    fi
    EXA_PASSWORD="$(cat "{pwfile}")"; export EXA_PASSWORD
fi
_waited=0
while [ "$_waited" -lt 120 ]; do
    curl -sk --max-time 2 "https://$EXA_HOST:$EXA_PORT/" >/dev/null 2>&1
    [ $? -ne 7 ] && break
    sleep 3; _waited=$((_waited + 3))
done
_fails=0
while :; do
    _t0=$(date +%s 2>/dev/null || echo 0)
    "$ENGINE" "$@"; _rc=$?
    [ "$_rc" -eq 0 ] && exit 0
    _t1=$(date +%s 2>/dev/null || echo 0)
    if [ $((_t1 - _t0)) -lt 60 ]; then _fails=$((_fails + 1)); else _fails=1; fi
    if [ "$_fails" -ge 5 ]; then
        printf 'exasol-scheduler: engine failed %s times in quick succession (last exit %s) - giving up.\\n' "$_fails" "$_rc" >&2
        printf 'Diagnose with: exakit logs exasol-scheduler   then restart with: exakit start\\n' >&2
        printf 'gave up after %s rapid failures (last exit %s) at %s\\n' "$_fails" "$_rc" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "{giveup}"
        exit "$_rc"
    fi
    printf 'exasol-scheduler: engine exited (%s) - restarting in 5s (attempt %s/5)\\n' "$_rc" "$_fails" >&2
    sleep 5
done
"""


class Lifecycle(BinaryLifecycle):
    @property
    def pidfile(self) -> Path:
        return self.home / "exasol-scheduler.pid"

    @property
    def giveup(self) -> Path:
        return self.home / "gave-up"

    @property
    def log_file(self) -> Path:
        return self.ctx.paths.logs / "exasol-scheduler.log"

    @property
    def launcher(self) -> Path:
        return self.ctx.paths.bin_dir / "exasol-scheduler"

    # --- release naming ------------------------------------------------------------

    def arch_word(self) -> str:
        return "arm64" if self.ctx.platform.arch == "aarch64" else "x86_64"

    def asset_name(self, version: str) -> str:
        return f"exasol-scheduler-{self.ctx.platform.os}-{self.arch_word()}"

    def digest_key(self, version: str) -> str:
        return f"{self.ctx.platform.os}-{self.arch_word()}"

    def applicable(self) -> tuple[bool, str]:
        if self.ctx.platform.os not in ("macos", "linux"):
            return False, f"no prebuilt scheduler binary is published for this platform ({self.ctx.platform.os}/{self.ctx.platform.arch})"
        return True, ""

    def repo(self) -> str:
        explicit = self.ctx.env.get("EXAKIT_EXASOL_SCHEDULER_MIRROR_REPO")
        if explicit:
            return explicit
        manifest = self.ctx.manifest_or_none()
        source = manifest.get("kit.source") if manifest else None
        if isinstance(source, str) and "@" in source and "/" in source.split("@")[0]:
            return source.split("@")[0]
        return self.ctx.kit_repo

    def release_tag(self, version: str) -> str:
        explicit = self.ctx.env.get("EXAKIT_EXASOL_SCHEDULER_RELEASE_TAG")
        if explicit:
            return explicit
        doc = self.ctx.versions.current()
        pinned = doc.value("components.exasol-scheduler.release") if doc and self.pin_applies(version) else None
        return pinned or f"exasol-scheduler-{version}"

    def system_present(self) -> bool:
        found = self.ctx.runner.which("exasol_scheduler")
        return bool(found) and Path(found).resolve() != self.engine.resolve()

    # --- the database user --------------------------------------------------------------

    def ensure_db_user(self) -> None:
        from exakit.app.runtime_ops import credentials, exapump, profile_name  # noqa: PLC0415
        pump = exapump(self.ctx)
        if pump is None:
            raise Failed("exapump is required to create the scheduler's database user")
        store: CredentialStore = credentials(self.ctx)
        password = store.read("exasol_scheduler_password")
        if not CredentialStore.is_token(password):
            password = CredentialStore.new_token()
            store.store("exasol_scheduler_password", password)
        user = DB_USER.upper()
        profile = profile_name(self.ctx)
        probe = pump.sql(profile, f"SELECT CASE WHEN EXISTS (SELECT 1 FROM EXA_DBA_USERS WHERE USER_NAME = '{user}') "
                                  "THEN 'EXAKIT_SCHED_USER_PRESENT' ELSE 'EXAKIT_SCHED_USER_MISSING' END AS STATUS")
        if not probe.ok:
            raise Failed("the dedicated database user could not be created - is the database running? (exakit start)", remedy="exakit start")
        verb = "ALTER" if "EXAKIT_SCHED_USER_PRESENT" in probe.out else "CREATE"
        statements = [f'{verb} USER {user} IDENTIFIED BY "{password}"', f"GRANT CREATE SESSION TO {user}",
                      f"GRANT CREATE SCHEMA TO {user}", f"GRANT CREATE TABLE TO {user}"]
        for sql in statements:
            if not pump.sql(profile, sql).ok:
                raise Failed("the dedicated database user could not be created - is the database running? (exakit start)", remedy="exakit start")

    def schema_present(self) -> bool:
        from exakit.app.runtime_ops import exapump, profile_name  # noqa: PLC0415
        pump = exapump(self.ctx)
        if pump is None:
            return False
        done = pump.sql(profile_name(self.ctx), f"SELECT CASE WHEN EXISTS (SELECT 1 FROM EXA_SCHEMAS WHERE SCHEMA_NAME = '{SCHEMA}') "
                                                "THEN 'EXAKIT_SCHED_SCHEMA_PRESENT' ELSE 'EXAKIT_SCHED_SCHEMA_MISSING' END AS STATUS")
        return done.ok and "EXAKIT_SCHED_SCHEMA_PRESENT" in done.out

    def revoke_bootstrap(self) -> None:
        if self.recorded("bootstrap_revoked") is True:
            return
        from exakit.app.runtime_ops import exapump, profile_name  # noqa: PLC0415
        pump = exapump(self.ctx)
        if pump:
            pump.sql(profile_name(self.ctx), f"REVOKE CREATE SCHEMA FROM {DB_USER.upper()}")
            pump.sql(profile_name(self.ctx), f"REVOKE CREATE TABLE FROM {DB_USER.upper()}")
        self.record(bootstrap_revoked=True)

    # --- launcher, install, validate ----------------------------------------------------------

    def launcher_content(self) -> str | None:
        from exakit.app.runtime_ops import credentials  # noqa: PLC0415
        dsn, _, _ = self.runtime_credentials()
        host, _, port = dsn.rpartition(":")
        return LAUNCHER.format(pidfile=self.pidfile, engine=self.engine, giveup=self.giveup, host=host or "127.0.0.1",
                               port=port if port.isdigit() else "8563", user=DB_USER, schema=SCHEMA,
                               pwfile=credentials(self.ctx).path("exasol_scheduler_password"))

    def after_engine(self, version: str) -> None:
        self.ensure_db_user()
        self.record(db_user=DB_USER, schema=SCHEMA, bootstrap_revoked=False)

    def validate(self) -> None:
        if not self.engine.exists():
            self.ctx.ui.warn("exasol-scheduler engine is missing - repair with: exakit update exasol-scheduler")
            return
        try:
            self.start()
        except Failed:
            return
        if wait_for(self.schema_present, seconds=60, every=3):
            self.revoke_bootstrap()
            self.record(validated=True)
            self.ctx.ui.ok(f"exasol-scheduler is running - define jobs in {SCHEMA}.SCHED_TASKS")
        else:
            self.ctx.ui.warn("exasol-scheduler did not create its schema within 60s - see: exakit logs exasol-scheduler")

    # --- service -----------------------------------------------------------------------------------

    def pids(self) -> list[int]:
        pids: set[int] = set()
        try:
            pid = int(self.pidfile.read_text().strip())
            if self.ctx.runner.run(["kill", "-0", str(pid)], timeout=5).ok:
                pids.add(pid)
        except (OSError, ValueError):
            pass
        found = self.ctx.runner.run(["pgrep", "-f", str(self.engine)], timeout=10)
        pids.update(int(p) for p in found.out.split() if p.isdigit())
        return sorted(pids)

    def status(self) -> str:
        if not self.launcher.exists():
            return "not installed"
        if self.pids():
            return "running"
        if self.giveup.exists():
            words = " ".join(self.giveup.read_text(errors="replace").split()[:6])
            return f"stopped ({words} - diagnose: exakit logs exasol-scheduler, restart: exakit start)"
        return "stopped"

    def start(self) -> None:
        if not self.launcher.exists():
            self.ctx.ui.warn("exasol-scheduler is not installed - add it with: exakit marketplace")
            raise Failed("exasol-scheduler is not installed", remedy="exakit marketplace exasol-scheduler")
        if self.pids():
            self.ctx.ui.ok("exasol-scheduler is already running")
            return
        self.giveup.unlink(missing_ok=True)
        self.ctx.paths.logs.mkdir(parents=True, exist_ok=True)
        with self.log_file.open("a") as log:
            subprocess.Popen([str(self.launcher)], stdout=log, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL, start_new_session=True)
        if wait_for(lambda: bool(self.pids()), seconds=4, every=1):
            self.ctx.ui.ok("exasol-scheduler started")
            return
        self.ctx.ui.warn(f"exasol-scheduler did not stay up - see {self.log_file}")
        raise Failed("exasol-scheduler did not start", remedy="exakit logs exasol-scheduler")

    def stop(self) -> None:
        pids = self.pids()
        if not pids:
            self.ctx.ui.ok("exasol-scheduler is already stopped")
            return
        for pid in pids:
            self.ctx.runner.run(["pkill", "-P", str(pid)], timeout=5)
            self.ctx.runner.run(["kill", str(pid)], timeout=5)
        wait_for(lambda: not self.pids(), seconds=3, every=0.5)
        for pid in self.pids():
            self.ctx.runner.run(["kill", "-9", str(pid)], timeout=5)
        self.pidfile.unlink(missing_ok=True)
        self.ctx.ui.ok("exasol-scheduler stopped (missed occurrences are not replayed on restart)")

    def service(self) -> ServiceHooks:
        return ServiceHooks(status=self.status, start=self.start, stop=self.stop, url=lambda: None,
                            log_path=lambda: self.log_file, autostart=lambda: ServiceSpec("exasol-scheduler", (str(self.launcher),)))

    def summary(self) -> str | None:
        return f"SQL jobs in {SCHEMA}.SCHED_TASKS"

    # --- update and uninstall ---------------------------------------------------------------------

    def update(self) -> None:
        was_running = bool(self.pids())
        had_install = self.installed_version() is not None
        if was_running:
            self.stop()
        target = self.target_version()
        if self.installed_version() == target:
            self.write_launchers()
            self.ctx.ui.ok(f"exasol-scheduler is already current ({target})")
            if was_running:
                self.start()
            return
        self.ctx.ui.info(f"Updating exasol-scheduler {self.installed_version() or 'not installed'} -> {target}")
        self.ctx.env = {**dict(self.ctx.env), "EXAKIT_FORCE_COMPONENT_INSTALL": "1"}
        self.install(target)
        if was_running or not had_install:
            self.validate()
        self.ctx.manifest_store.update(lambda m: m.set(f"desired.{self.key}", target))
        self.ctx.ui.ok("exasol-scheduler updated; database data was not changed")

    def uninstall(self, *, dry_run: bool) -> list[str]:
        from exakit.app.runtime_ops import credentials, exapump, profile_name  # noqa: PLC0415
        if not dry_run:
            try:
                self.stop()
            except Failed:
                pass
        removed = self.remove_paths([self.home, self.launcher, credentials(self.ctx).path("exasol_scheduler_password")], dry_run=dry_run)
        if dry_run:
            self.ctx.ui.text(f"  will drop:   database user {DB_USER} (the {SCHEMA} schema and its history stay - they are your data)")
            return removed
        pump = exapump(self.ctx)
        if pump:
            pump.sql(profile_name(self.ctx), f"DROP USER {DB_USER.upper()}")
        self.forget()
        self.ctx.ui.ok(f"exasol-scheduler removed (the {SCHEMA} schema was left in place) - reinstall any time with: exakit marketplace")
        return removed
