"""JSON Tables: a Python package from a verified wheel plus a prebuilt ingest engine, both from the kit's own release."""

from __future__ import annotations

import json
import tarfile
from pathlib import Path

from exakit.adapters.net.github import download_url, release_assets
from exakit.domain.errors import Failed
from exakit.lifecycles.base import make_executable, temp_dir
from exakit.lifecycles.python_venv import PythonVenvLifecycle

SHIM = """#!/bin/sh
# cargo shim - generated by the Exasol Personal Local Starter Kit for JSON Tables.
# The package shells out to `cargo run` for its ingest engine; this answers that one call
# with the prebuilt engine and hands anything else to a real cargo on PATH.
if [ "$1" = "run" ]; then
    _jt_is_ingest=0
    for _jt_arg in "$@"; do case "$_jt_arg" in *json_tables_ingest*) _jt_is_ingest=1 ;; esac; done
    if [ "$_jt_is_ingest" = "1" ]; then
        _jt_seen=0
        for _jt_arg in "$@"; do
            if [ "$_jt_seen" = "1" ]; then set -- "$@" "$_jt_arg"; fi
            [ "$_jt_arg" = "--" ] && _jt_seen=1
            shift
        done
        exec "{engine}" "$@"
    fi
fi
_jt_real=""; _jt_oldifs="$IFS"; IFS=:
for _jt_dir in $PATH; do
    [ "$_jt_dir" = "{shimdir}" ] && continue
    if [ -x "$_jt_dir/cargo" ]; then _jt_real="$_jt_dir/cargo"; break; fi
done
IFS="$_jt_oldifs"
if [ -n "$_jt_real" ]; then exec "$_jt_real" "$@"; fi
printf 'cargo: not installed, and this is not the JSON Tables ingest call the kit can answer.\\n' >&2
exit 127
"""

LAUNCHER = """#!/bin/sh
# exasol-json-tables launcher - generated by the Exasol Personal Local Starter Kit. Regenerated by:
#   exakit update json-tables
PATH="{shimdir}:$PATH"
export PATH
exec "{script}" "$@"
"""


class Lifecycle(PythonVenvLifecycle):
    @property
    def home(self) -> Path:
        return self.ctx.paths.home / "json-tables"

    @property
    def engine(self) -> Path:
        return self.home / "libexec" / "json_to_parquet"

    @property
    def shim_dir(self) -> Path:
        return self.home / "shim"

    @property
    def launcher(self) -> Path:
        return self.ctx.paths.bin_dir / "exasol-json-tables"

    # --- platform and versions ------------------------------------------------------

    def engine_asset(self) -> str | None:
        """The prebuilt ingest engine for this platform, named by the catalog; None where none is published."""
        name = (self.addon.source.get("engine_assets") or {}).get(self.ctx.platform.platform_key)
        return str(name) if name else None

    def applicable(self) -> tuple[bool, str]:
        if self.engine_asset() is None:
            return False, f"no prebuilt ingest engine is published for this platform ({self.ctx.platform.os}/{self.ctx.platform.arch})"
        return True, ""

    def installed_version(self) -> str | None:
        recorded = self.recorded("version")
        if not recorded or not self.python.exists() or not self.engine.exists():
            return None
        if not self.ctx.runner.run([str(self.python), "-c", "import exasol_json_tables"], timeout=60).ok:
            return None
        return str(recorded)

    def system_present(self) -> bool:
        found = self.ctx.runner.which("exasol-json-tables")
        if found and Path(found).resolve() != self.launcher.resolve():
            return True
        ambient = self.ctx.runner.which("python3") or self.ctx.runner.which("python")
        if ambient and str(self.venv) not in ambient and str(self.ctx.paths.home) not in ambient:
            return self.ctx.runner.run([ambient, "-c", "import exasol_json_tables"], timeout=30).ok
        return False

    def mirror_repo(self) -> str:
        explicit = self.ctx.env.get("EXAKIT_JSON_TABLES_MIRROR_REPO")
        if explicit:
            return explicit
        manifest = self.ctx.manifest_or_none()
        source = manifest.get("kit.source") if manifest else None
        if isinstance(source, str) and "@" in source and "/" in source.split("@")[0]:
            return source.split("@")[0]
        return self.ctx.kit_repo if self.addon.source.get("mirror") == "kit" else str(self.addon.source["repo"])

    def release_tag(self, version: str) -> str:
        explicit = self.ctx.env.get("EXAKIT_JSON_TABLES_MIRROR_TAG")
        if explicit:
            return explicit
        doc = self.ctx.versions.current()
        pinned = doc.value("components.json-tables.release") if doc and self.pin_applies(version) else None
        return pinned or str(self.addon.source.get("tag", "json-tables-{version}")).format(version=version)

    def wheel_name(self, version: str) -> str | None:
        doc = self.ctx.versions.current()
        if doc and self.pin_applies(version) and doc.value("components.json-tables.wheel"):
            return str(doc.value("components.json-tables.wheel"))
        assets = release_assets(self.mirror_repo(), self.release_tag(version), self.ctx.net, endpoints=self.ctx.catalog.kit.endpoints,
                                token=self.ctx.env.get("GITHUB_TOKEN"), cache_dir=self.ctx.paths.releases_cache) or []
        wheels = [a.name for a in assets if a.name.endswith(".whl")]
        return wheels[0] if wheels else None

    # --- install ----------------------------------------------------------------------------

    def restore_package_data(self, version: str) -> None:
        site = self.ctx.runner.run([str(self.python), "-c", "import exasol_json_tables, os; print(os.path.dirname(exasol_json_tables.__file__))"], timeout=30)
        if not site.ok or not site.out.strip():
            return
        target = Path(site.out.strip())
        with temp_dir("exakit-jt-src-") as tmp:
            archive = Path(tmp) / "src.tar.gz"
            try:
                ref = str(self.addon.source.get("sources", "{version}")).format(version=version)
                self.ctx.net.fetch(self.ctx.catalog.kit.endpoints.url("archive_ref", repo=str(self.addon.source["repo"]), ref=ref), archive,
                                   what="json-tables sources")
                with tarfile.open(archive) as tar:
                    tar.extractall(tmp, filter="data")
            except Exception as err:
                self.ctx.log.line("WARN", f"json-tables package data not restored: {err}")
                return
            for src_dir in Path(tmp).glob("*/python/exasol_json_tables"):
                for file in src_dir.rglob("*"):
                    if file.is_file() and file.suffix != ".py":
                        dest = target / file.relative_to(src_dir)
                        if not dest.exists():
                            dest.parent.mkdir(parents=True, exist_ok=True)
                            dest.write_bytes(file.read_bytes())

    def write_launchers(self) -> None:
        self.shim_dir.mkdir(parents=True, exist_ok=True)
        shim = self.shim_dir / "cargo"
        shim.write_text(SHIM.format(engine=self.engine, shimdir=self.shim_dir), encoding="utf-8")
        make_executable(shim)
        self.write_launcher("exasol-json-tables", LAUNCHER.format(shimdir=self.shim_dir, script=self.uv().bin_of(self.venv, "exasol-json-tables")))

    def install(self, version: str) -> None:
        ok, reason = self.applicable()
        if not ok:
            raise Failed(reason)
        wheel = self.wheel_name(version)
        if not wheel:
            raise Failed(f"the prebuilt release '{self.release_tag(version)}' was not found in {self.mirror_repo()} - "
                         "check the network (GITHUB_TOKEN raises the API limit), then run: exakit marketplace json-tables")
        self.ctx.ui.info(f"Installing JSON Tables {version} (prebuilt)")
        self.ensure_venv()
        repo, tag = self.mirror_repo(), self.release_tag(version)
        with temp_dir("exakit-jt-") as tmp:
            wheel_path = Path(tmp) / wheel
            self.fetch_verified(download_url(repo, tag, wheel, endpoints=self.ctx.catalog.kit.endpoints), wheel_path, digest=self.published_digest(version, "wheel"),
                                what=wheel, repo=repo, tag=tag, asset=wheel)
            self.uv().pip_install(self.python, str(wheel_path))
            self.restore_package_data(version)
            asset = self.engine_asset() or ""
            staged = Path(tmp) / "engine"
            self.fetch_verified(download_url(repo, tag, asset, endpoints=self.ctx.catalog.kit.endpoints), staged, digest=self.published_digest(version, self.ctx.platform.platform_key),
                                what=asset, repo=repo, tag=tag, asset=asset)
            self.engine.parent.mkdir(parents=True, exist_ok=True)
            staged.replace(self.engine)
        make_executable(self.engine)
        if not self.ctx.runner.run([str(self.engine), "--help"], timeout=30).ok:
            raise Failed("the prebuilt ingest engine does not run on this machine (see log)")
        self.write_launchers()
        self.record(version=version, venv=str(self.venv), python=str(self.python), engine=str(self.engine), command=str(self.launcher))
        self.ctx.ui.ok(f"JSON Tables installed: {self.venv}")

    def validate(self) -> None:
        if not self.python.exists():
            return
        if not self.ctx.runner.run([str(self.python), "-c", "import exasol_json_tables"], timeout=60).ok:
            self.ctx.ui.warn("JSON Tables did not import from its environment - repair with: exakit update json-tables")
            self.record(validated=False)
            return
        with temp_dir("exakit-jt-check-") as tmp:
            sample = Path(tmp) / "sample.json"
            sample.write_text(json.dumps([{"id": 1, "name": "alpha"}, {"id": 2, "name": "beta"}]))
            out = Path(tmp) / "out"
            done = self.ctx.runner.run([str(self.engine), "--input", str(sample), "--output-dir", str(out)], timeout=120,
                                       env={"PATH": f"{self.shim_dir}:{self.ctx.env.get('PATH', '')}"})
            parquet = list(out.rglob("*.parquet")) if out.exists() else []
        if done.ok and parquet:
            self.record(validated=True)
            self.ctx.ui.ok("Ingest works: JSON in, Parquet out")
        else:
            self.record(validated=False)
            self.ctx.ui.warn("The JSON Tables engine did not produce Parquet from a sample - see: exakit logs json-tables")

    def summary(self) -> str | None:
        return "ingest JSON: exasol-json-tables"

    def repair(self) -> None:
        self.write_launchers()

    def uninstall(self, *, dry_run: bool) -> list[str]:
        removed = self.remove_paths([self.venv, self.home, self.launcher], dry_run=dry_run)
        if not dry_run:
            self.forget()
            self.ctx.ui.ok("JSON Tables removed - reinstall any time with: exakit marketplace")
        return removed
